import 'package:flutter/widgets.dart';

class PHS with ChangeNotifier {
  String? staff_name1,
      staff_position1,
      staff_phoneNumber1,
      staff_bankAccountName1,
      staff_accountNumber1,
      staff_bankName1,
      staff_commentary1,
      createdDate,
      id,
      trackingDate,
      staffResignationAllowance1,
      staffYearAllowanceBalance,
      staffEndOfYearAllowanceTxtV,
      staffBonus1,
      loanPaid,
      remainingLoan,
      staffDeduction1,
      staffLoan1,
      staffLoanPayPerMonth1,
      staffSavings1,
      staffSavingsPerMonth1,
      staffSalary1,
      staff_salary_increment1;
  double? payable;

  PHS(
      {this.staff_name1,
      this.staff_position1,
      this.staff_phoneNumber1,
      this.staffSalary1,
      this.staffBonus1,
      this.staffDeduction1,
      this.staffSavings1,
      this.staffSavingsPerMonth1,
      this.staffLoan1,
      this.staffLoanPayPerMonth1,
      this.staff_bankAccountName1,
      this.staff_accountNumber1,
      this.staff_bankName1,
      this.staff_commentary1,
      this.createdDate,
      this.staff_salary_increment1,
      this.id,
      this.payable,
      this.trackingDate,
      this.remainingLoan,
      this.loanPaid,
      this.staffResignationAllowance1,
      this.staffYearAllowanceBalance,
      this.staffEndOfYearAllowanceTxtV});

  factory PHS.fromMap(map) {
    return PHS(
      staff_name1: map['staff_name1'],
      staff_position1: map['staff_position1'],
      staff_phoneNumber1: map['staff_phoneNumber1'],
      staffSalary1: map['staffSalary1'],
      staffBonus1: map['staffBonus1'],
      staffDeduction1: map['staffDeduction1'],
      staffSavings1: map['staffSavings1'],
      staffSavingsPerMonth1: map['staffSavingsPerMonth1'],
      staffLoan1: map['staffLoan1'],
      staffLoanPayPerMonth1: map['staffLoanPayPerMonth1'],
      staff_bankAccountName1: map['staff_bankAccountName1'],
      staff_accountNumber1: map['staff_accountNumber1'],
      staff_bankName1: map['staff_bankName1'],
      staff_commentary1: map['staff_commentary1'],
      createdDate: map['createdDate'],
      staff_salary_increment1: map['staff_salary_increment1'],
      id: map['id'],
      payable: map['payable'],
      trackingDate: map['trackingDate'],
      remainingLoan: map['remainingLoan'],
      loanPaid: map['loanPaid'],
      staffResignationAllowance1: map['staffResignationAllowance1'],
      staffYearAllowanceBalance: map['staffYearAllowanceBalance'],
      staffEndOfYearAllowanceTxtV: map['staffEndOfYearAllowanceTxtV'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'staff_name1': staff_name1,
      'staff_position1': staff_position1,
      'staff_phoneNumber1': staff_phoneNumber1,
      'staffSalary1': staffSalary1,
      'staffBonus1': staffBonus1,
      'staffDeduction1': staffDeduction1,
      'staffSavings1': staffSavings1,
      'staffSavingsPerMonth1': staffSavingsPerMonth1,
      'staffLoan1': staffLoan1,
      'staffLoanPayPerMonth1': staffLoanPayPerMonth1,
      'staff_bankAccountName1': staff_bankAccountName1,
      'staff_accountNumber1': staff_accountNumber1,
      'staff_bankName1': staff_bankName1,
      'staff_commentary1': staff_commentary1,
      'createdDate': createdDate,
      'staff_salary_increment1': staff_salary_increment1,
      'id': id,
      'payable': payable,
      'trackingDate': trackingDate,
      'remainingLoan': remainingLoan,
      'loanPaid': loanPaid,
      'staffResignationAllowance1': staffResignationAllowance1,
      'staffYearAllowanceBalance': staffYearAllowanceBalance,
      'staffEndOfYearAllowanceTxtV': staffEndOfYearAllowanceTxtV
    };
  }
}
