// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG36Z2cJONoWvYgv9ewyyPEm1KYAFDodI',
    appId: '1:618471527452:web:5cff687794d584d0c33bd9',
    messagingSenderId: '618471527452',
    projectId: 'phrankstarmanagement',
    authDomain: 'phrankstarmanagement.firebaseapp.com',
    storageBucket: 'phrankstarmanagement.appspot.com',
    measurementId: 'G-X8S4VKEGPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDeiIWPpS6vhh858SDyNJznpx5zC1YgeE',
    appId: '1:618471527452:android:14096a013d38e113c33bd9',
    messagingSenderId: '618471527452',
    projectId: 'phrankstarmanagement',
    storageBucket: 'phrankstarmanagement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWumtRhW5IMGuTnnbt4OI05gg-BKe9Mgo',
    appId: '1:618471527452:ios:d3a1725bb623a7f8c33bd9',
    messagingSenderId: '618471527452',
    projectId: 'phrankstarmanagement',
    storageBucket: 'phrankstarmanagement.appspot.com',
    iosClientId:
        '618471527452-r4pf69pod3rt5k8ser4kksvk2h1red2l.apps.googleusercontent.com',
    iosBundleId: 'com.potentnetwork.phrankstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWumtRhW5IMGuTnnbt4OI05gg-BKe9Mgo',
    appId: '1:618471527452:ios:a6991bb18666df6bc33bd9',
    messagingSenderId: '618471527452',
    projectId: 'phrankstarmanagement',
    storageBucket: 'phrankstarmanagement.appspot.com',
    iosClientId:
        '618471527452-efbqroatagck5hoqjglerqtsmvjc3eme.apps.googleusercontent.com',
    iosBundleId: 'com.potentnetwork.phrankstar.RunnerTests',
  );
}
